//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteDatabaseConnection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Windows;

    public partial class SzafaSQLiteEntities : DbContext
    {
        public SzafaSQLiteEntities()
            : base("name=SzafaSQLiteEntities")
        {
            //Database.SetInitializer<SzafaSQLiteEntities>(new SzafaDbInitializer());
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clothes> clothes { get; set; }
        public virtual DbSet<types> types { get; set; }

        public class SzafaDbInitializer : IDatabaseInitializer<SzafaSQLiteEntities>
        {
            public void InitializeDatabase(SzafaSQLiteEntities context)
            {
                bool exists = context.Database.Exists();
                if (!exists)
                {
                    MessageBox.Show("No database found");
                }
            }
        }
    }
}
